
# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm --prefix board-game-statistics install
  displayName: 'Frontend - install'

- script: |
    npm --prefix board-game-statistics run build
  displayName: 'Frontend - build'

- script: |
    mvn -f board-game-statistics-api package
  displayName: 'Backend - build and test'
