
# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildAndTestFrontend
  displayName: Build and Test Frontend
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'board-game-statistics'
    displayName: 'Npm Install'

  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'board-game-statistics'
      customCommand: 'run prettier'
    displayName: 'Prettier'

  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'board-game-statistics'
      customCommand: 'run lint'
    displayName: 'Lint'

  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'board-game-statistics'
      customCommand: 'run build'
    displayName: 'Build'

- job: BuildAndTestBackend
  displayName: Build and Test Backend
  steps:
  - task: Maven@4
    env:
      BGS_DB_USERNAME: ""
      BGS_DB_PASSWORD: ""
      BGS_ADMIN_PASSWORD: ""
      BGS_MAIL_USERNAME: $(MAIL_USERNAME)
      BGS_MAIL_PASSWORD: $(MAIL_PASSWORD)
    inputs:
      mavenPomFile: 'board-game-statistics-api/pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
      goals: 'test'
    displayName: 'Build and test'
