INSERT INTO bgs.account (email, password, first_name, last_name) VALUES
('alice@example.com', ?, 'Alice', 'Smith'),
('bob@example.com', ?, 'Bob', 'Johnson'),
('carol@example.com', ?, 'Carol', 'Williams'),
('dave@example.com', ?, 'Dave', 'Brown'),
('eve@example.com', ?, 'Eve', 'Davis'),
('frank@example.com', ?, 'Frank', 'Miller'),
('grace@example.com', ?, 'Grace', 'Wilson'),
('matthew@adler.id.au', ?, 'Matthew', 'Adler'),
('henry@example.com', ?, 'Henry', 'Taylor'),
('iris@example.com', ?, 'Iris', 'Anderson'),
('jack@example.com', ?, 'Jack', 'Thomas'),
('kate@example.com', ?, 'Kate', 'Jackson'),
('liam@example.com', ?, 'Liam', 'White'),
('maya@example.com', ?, 'Maya', 'Harris'),
('noah@example.com', ?, 'Noah', 'Martin'),
('olivia@example.com', ?, 'Olivia', 'Garcia'),
('paul@example.com', ?, 'Paul', 'Rodriguez'),
('quinn@example.com', ?, 'Quinn', 'Lewis'),
('ruby@example.com', ?, 'Ruby', 'Lee'),
('sam@example.com', ?, 'Sam', 'Walker'),
('bianca@example.com', ?, 'Bianca', 'Bankingman');

-- Game Groups
INSERT INTO bgs.game_group (group_name, creation_time) VALUES
('Board Gamers', NOW() - INTERVAL '10 days'),
('Strategy Masters', NOW() - INTERVAL '8 days'),
('Casual Players', NOW() - INTERVAL '6 days'),
('Weekend Warriors', NOW() - INTERVAL '4 days'),
('Family Fun', NOW() - INTERVAL '2 days'),
('Night Owls', NOW() - INTERVAL '1 day');

-- Group Memberships
INSERT INTO bgs.group_membership (group_id, account_id, permissions_mask, join_timestamp) VALUES
(1, 1, 0, NOW() - INTERVAL '9 days'),
(1, 2, 1, NOW() - INTERVAL '8 days'),
(2, 3, 2, NOW() - INTERVAL '7 days'),
(2, 4, 3, NOW() - INTERVAL '6 days'),
(3, 5, 4, NOW() - INTERVAL '5 days'),
(3, 6, 5, NOW() - INTERVAL '4 days'),
(4, 7, 6, NOW() - INTERVAL '3 days'),
(5, 1, 7, NOW() - INTERVAL '2 days'),
(5, 3, 8, NOW() - INTERVAL '1 day'),
(6, 2, 9, NOW()),
(6, 8, 10, NOW() - INTERVAL '12 hours'),
(1, 8, 11, NOW() - INTERVAL '10 days'),
(1, 9, 12, NOW() - INTERVAL '9 days'),
(1, 10, 13, NOW() - INTERVAL '8 days'),
(2, 11, 14, NOW() - INTERVAL '7 days'),
(2, 12, 15, NOW() - INTERVAL '6 days'),
(3, 13, 1, NOW() - INTERVAL '5 days'),
(3, 14, 2, NOW() - INTERVAL '4 days'),
(4, 15, 3, NOW() - INTERVAL '3 days'),
(4, 16, 4, NOW() - INTERVAL '2 days'),
(5, 17, 5, NOW() - INTERVAL '1 day'),
(5, 18, 6, NOW() - INTERVAL '12 hours'),
(6, 19, 7, NOW() - INTERVAL '6 hours'),
(6, 20, 8, NOW() - INTERVAL '3 hours'),
(2, 9, 9, NOW() - INTERVAL '5 days'),
(3, 10, 10, NOW() - INTERVAL '4 days'),
(4, 11, 11, NOW() - INTERVAL '3 days'),
(5, 12, 12, NOW() - INTERVAL '2 days'),
(6, 13, 13, NOW() - INTERVAL '1 day'),
(1, 14, 14, NOW() - INTERVAL '12 hours'),
(2, 15, 15, NOW() - INTERVAL '6 hours'),
(3, 16, 1, NOW() - INTERVAL '3 hours'),
(4, 17, 2, NOW() - INTERVAL '2 hours'),
(5, 19, 3, NOW() - INTERVAL '1 hour'),
(1, 20, 4, NOW() - INTERVAL '30 minutes'),
(3, 1, 5, NOW() - INTERVAL '7 days'),
(4, 2, 6, NOW() - INTERVAL '5 days'),
(6, 3, 7, NOW() - INTERVAL '3 days'),
(3, 4, 8, NOW() - INTERVAL '4 days'),
(5, 4, 9, NOW() - INTERVAL '2 days'),
(1, 5, 10, NOW() - INTERVAL '6 days'),
(4, 5, 11, NOW() - INTERVAL '3 days'),
(2, 6, 12, NOW() - INTERVAL '5 days'),
(5, 6, 13, NOW() - INTERVAL '2 days'),
(1, 7, 14, NOW() - INTERVAL '6 days'),
(6, 7, 15, NOW() - INTERVAL '1 day'),
(3, 8, 1, NOW() - INTERVAL '4 days'),
(5, 9, 2, NOW() - INTERVAL '3 days'),
(6, 10, 3, NOW() - INTERVAL '2 days'),
(6, 11, 4, NOW() - INTERVAL '1 day'),
(1, 12, 5, NOW() - INTERVAL '4 days'),
(2, 13, 6, NOW() - INTERVAL '3 days'),
(5, 14, 7, NOW() - INTERVAL '2 days'),
(6, 15, 8, NOW() - INTERVAL '1 day'),
(1, 16, 9, NOW() - INTERVAL '3 days'),
(6, 17, 10, NOW() - INTERVAL '1 day'),
(2, 18, 11, NOW() - INTERVAL '4 days'),
(6, 18, 12, NOW() - INTERVAL '2 days'),
(1, 19, 13, NOW() - INTERVAL '2 days'),
(4, 20, 14, NOW() - INTERVAL '1 day');
